---
apt_packages:
  - apt-transport-https
  - code
  #- com.github.stsdc.monitor
  - containerd.io
  - curl
  - docker-ce
  - docker-ce-cli
  - elementary-sdk
  - git
  - libadwaita-1-dev
  - libgranite-7-dev
  - granite-7-demo
  - libgtksourceview-5-dev
  - libsecret-1-dev
  - libsoup2.4-dev
  - libsqlite3-dev
  - libvala-dev
  - meson
  - net-tools
  - neofetch
  - python3-pip
  - vim