---
- name: Install package
  become: yes
  apt:
    name: git
    state: present

- name: Copy config
  become: yes
  template:
    src: .gitconfig.j2
    dest: "/home/{{ user_name }}/.gitconfig"
    owner: "{{ user_name }}"
    group: "{{ user_group }}"

